# Generated by Django 4.0.3 on 2022-04-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='timestamp',
        ),
    ]
