# Generated by Django 4.0.3 on 2022-04-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='name',
            field=models.CharField(default='name', max_length=30),
        ),
    ]
