# Generated by Django 4.0.3 on 2022-04-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_account_timestamp_alter_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('WD', 'Withdrawal'), ('DP', 'Deposit'), ('TF', 'Transfer')], max_length=30),
        ),
    ]
