# Generated by Django 4.0.4 on 2022-05-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
