# Generated by Django 4.0.3 on 2022-04-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_transaction_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
