# Generated by Django 4.0.4 on 2022-05-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_delete_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
