# Generated by Django 4.0.3 on 2022-04-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_loan_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='status',
            new_name='pending',
        ),
    ]
